#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Make columns non-nullable."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1777139066"
down_revision = "3c1b8d0e7f52"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collections_collection", "depth", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "collections_collection",
        "num_records",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collections_collection",
        "num_records",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "collections_collection", "depth", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
