# -*- coding: utf-8 -*-
#
# Copyright (C) 2025 Ubiquity Press.
#
# invenio-collections is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.


name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    uses: inveniosoftware/workflows/.github/workflows/pypi-publish.yml@master
    secrets: inherit
